import { ArrowRight, Check, Cross, HeartPulse, LocateFixed, ShieldCheck, Sparkles } from "lucide-react";
import { HumanBody } from "@/components/HumanBody/HumanBody";

export default function Home({ onStart, onFindCare }: { onStart: () => void; onFindCare: () => void }) {
  return (
    <div className="site-shell">
      <header className="site-header"><a className="wordmark" href="#top" aria-label="MediSphere home"><span className="wordmark-mark"><Cross size={15} /></span>Medi<span>Sphere</span></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#safety">Safety</a><button type="button" onClick={onFindCare}>Find care</button><a href="#about">About</a></nav><button className="header-cta" type="button" onClick={onStart}>Start assessment <ArrowRight size={15} /></button></header>
      <main id="top">
        <section className="hero-section"><div className="hero-copy"><div className="quiet-badge"><span className="badge-pulse" /> Health guidance, made human</div><h1>Understand your symptoms.<br /><em>Know what to do next.</em></h1><p className="hero-lede">Describe what you are experiencing and get clear, AI-assisted guidance on the next appropriate step — without the overwhelm.</p><div className="hero-actions"><button className="button button-dark button-large" type="button" onClick={onStart}>Start health assessment <ArrowRight size={17} /></button><a className="learn-link" href="#how-it-works">See how it works <ArrowRight size={15} /></a></div><div className="hero-reassurance"><ShieldCheck size={17} /><span>Private by design</span><span className="reassurance-divider" /><span>Not a diagnosis</span></div></div><div className="hero-visual"><div className="visual-caption"><span className="caption-line" /><div><span className="small-label">A clearer picture</span><strong>Start by pointing to where it hurts.</strong></div></div><div className="hero-model-backdrop"><div className="body-orbit orbit-one" /><div className="body-orbit orbit-two" /><HumanBody /><div className="model-legend"><span><span className="legend-dot teal" /> Select an area</span><span><span className="legend-dot ink" /> Rotate freely</span></div></div></div></section>

        <section className="trust-strip"><div><span className="trust-number">01</span><strong>Start with the body</strong><p>Use an interactive anatomy view to locate the area that needs attention.</p></div><div><span className="trust-number">02</span><strong>Add the details</strong><p>Share symptoms, severity and context at your own pace.</p></div><div><span className="trust-number">03</span><strong>Leave with a next step</strong><p>Get calm guidance on whether to monitor, book care or act now.</p></div></section>

        <section className="principles-section" id="how-it-works"><div className="section-intro"><p className="eyebrow">Thoughtful by default</p><h2>Good health guidance starts with listening.</h2><p>We designed MediSphere to make the first conversation about your symptoms feel less clinical and more human.</p></div><div className="principles-grid"><article><div className="principle-icon"><HeartPulse size={19} /></div><h3>Progressive, not overwhelming</h3><p>One simple question at a time, with the context that matters and none of the unnecessary form-filling.</p></article><article><div className="principle-icon"><Sparkles size={19} /></div><h3>Useful, not definitive</h3><p>AI-assisted information helps you prepare for a conversation with a professional. It never replaces one.</p></article><article><div className="principle-icon"><LocateFixed size={19} /></div><h3>Ready for what is next</h3><p>When you need care, find nearby options and practical details in one place.</p></article></div></section>

        <section className="safety-section" id="safety"><div className="safety-mark"><ShieldCheck size={24} /></div><div><p className="eyebrow">A note on safety</p><h2>MediSphere is not a medical diagnosis.</h2><p>It is an AI-assisted health triage and information tool. If symptoms are severe, sudden, worsening or feel life-threatening, contact your local emergency services immediately.</p></div><button className="button button-outline" type="button" onClick={onFindCare}>Find nearby care <ArrowRight size={16} /></button></section>
        <section className="about-section" id="about"><div><p className="eyebrow">Made for the in-between moments</p><h2>When you are not sure what to do next.</h2></div><div><p>Not every symptom needs an emergency room. Not every question can wait. MediSphere helps you organize what you are feeling and choose a more informed next step.</p><div className="about-points"><span><Check size={15} /> Clear language</span><span><Check size={15} /> Human-centered design</span><span><Check size={15} /> Professional care, always part of the picture</span></div></div></section>
      </main>
      <footer className="site-footer"><a className="wordmark" href="#top"><span className="wordmark-mark"><Cross size={13} /></span>Medi<span>Sphere</span></a><span>AI-assisted health information, thoughtfully designed.</span><span>© 2026 MediSphere</span></footer>
    </div>
  );
}
